version: '3'
services:
  mongo:
    image: mongo:3.6
    container_name: tt-platte-mongo
  web:
    build: .
    container_name: tt-platte
    ports:
     - "8084:8080"
    environment:
     - SENDGRID_USER=user
     - SENDGRID_PASSWORD=secret
     - RECAPTCHA_SITE_KEY=secret
     - RECAPTCHA_SECRET_KEY=secret
     - MONGODB_URI=mongodb://mongo:27017/test 
    links:
     - mongo 
    depends_on: 
     - mongo
    command: nodemon -e js,pug app.js
    volumes:
     - .:/starter
     - /starter/node_modules
     
